version: '3.8'
services:
#  mongodb:
#    image: mongo
#    container_name: product-db
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    networks:
#      - product-network
#    volumes:
#      - mongodb:/data/db
  product-api:
    build: .
    #image: deegaem/product-app:1.0.0
    container_name: product-api
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product-db
     # SPRING_DATA_MONGODB_URI: mongodb://${DB_HOST}:27017/${DB_NAME}
#    networks:
#      - product-network
#    depends_on:
#      - mongodb
#networks:
#  product-network:
#    driver: bridge
#volumes:
#  mongodb: