version: '3.8'
services:
  product-db:
    image: mongodb/mongodb-community-server:latest
    container_name: product-db
    restart: unless-stopped
    expose:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nraboy
      MONGO_INITDB_ROOT_PASSWORD: password1234
    networks:
      - product-network
    volumes:
      - mongodb:/data/db
  product-app:
    build: .
    #image: deegaem/product-app:1.0.0
    container_name: product-app
    ports:
      - 8080:80
    environment:
      server.port: 80
      spring.application.name: product-app
      spring.profiles.active: dev
    networks:
      - product-network
    depends_on:
      - product-db
networks:
  product-network:
    driver: bridge
volumes:
  mongodb: